version: '3.8'

services:
  backend:
    build: ./backend
    depends_on:
      - mysql
    networks:
      - app-net
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-net

  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:

volumes:
  dbdata: