

services:
  backend:
    build: 
      context: "C:/Users/Admin/Documents/Exercício3 AmbienteDOCKER/docker-fullapp/backend"
    depends_on:
      - mysql
    networks:
      - app-net

  mysql:
    image: mysql:8
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: rootpass    
      MYSQL_DATABASE: testedb
    volumes:
      - mysql-data:/var/lib/mysql 
    networks:
      - app-net


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - backend 
    networks:
      - app-net


networks:
  app-net:

volumes:
  mysql-data:                 